hello-world-alahl1
msu-evrl/hello-world pull request #11
Opened 2017-05-31 17:09 UTC by alahl1

2017-06-01 02:15 UTC, Feyi1 requested changes
Your code is perfectly fine, but there are few changes that need to be made: 

1)  Your file doesn't have a designated filename extension. Is it .py or .java. 
2) The language you used requires the class name to be the same as the filename. You might want to check that since a format has been given for the filename.

Use https://github.com/msu-evrl/hello-world/pull/10 as a guide. Excellent, great job!

2017-06-01 14:53 UTC, knwachuk approved these changes

2017-06-01 14:55 UTC, knwachuk commented
Hello Sayo,

It seems she has addressed your concern. Please take another look and validate her changes.

2017-06-02 04:20 UTC, Feyi1 approved these changes

2017-06-02 04:34 UTC, merged