First pull request
msu-evrl/hello-world pull request #13
Opened 2017-06-02 04:06 UTC by rvirgil

2017-06-02 14:01 UTC, kydra1 approved these changes

2017-06-02 14:18 UTC, adlacilla approved these changes

2017-06-02 14:23 UTC, alahl1 requested changes
Please refer to the instructions regarding how to save the program file name.
Good job on the everything else. 

https://github.com/msu-evrl/hello-world/blob/master/CONTRIBUTING.md#file-name

2017-06-22 19:19 UTC, rvirgil reviewed
The name has been changed.

2017-06-24 00:51 UTC, knwachuk approved these changes

2017-08-04 18:34 UTC, merged